version: "3.4"

services:

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"

  lint:
    image: buildkite/plugin-linter
    command: ['--id', "ssh://git@github.com:lelia/test-buildkite-plugin"]
    volumes:
      - ".:/plugin"
