version: "3.4"

services:

  lint:
    image: buildkite/plugin-linter
    command: ['--id', "lelia/test"]
    volumes:
      - ".:/plugin"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
