name: test
description: Test the CI build process for Buildkite plugins
author: lelia
requirements:
  - bash
  - docker
  - docker-compose
configuration:
  properties:
    bool_param:
      type: boolean
    str_param:
      type: string
    int_param:
      type: integer
  required:
    - bool_param
  additionalProperties: false
